### ISSUE TITLE
Opening inventory causes crash!

### ISSUE THREAD

**Issue by canpolatbulbul** [SteveKunG/SkyBlockcatia#2]
Error:
java.lang.NoSuchMethodError: net.minecraft.client.gui.inventory.GuiContainer.getSlotUnderMouse()Lnet/minecraft/inventory/Slot;
	at net.minecraft.client.gui.inventory.GuiContainer.handler$keyTyped$zcl001(GuiContainer.java:1029)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:534)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SteveKunG** [comment]
Updating to 1.0.1 should fix the issue.
