### ISSUE TITLE
[Issue] SBCatia 1.0.14 still prevents game from startup

### ISSUE THREAD

**Issue by fmpreferences** [SteveKunG/SkyBlockcatia#48]
There wasn't an actual crash report for this for whatever reason, but this was in the game log:

[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method handler$updateMovementInput$zzf000(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.skyblockcatia.json:EntityPlayerSPMixin failed injection check, (0/1) succeeded. Using refmap mixins.skyblockcatia.refmap.json
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.client.main.Main.main(SourceFile:41)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:02:39] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:02:39] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method handler$updateMovementInput$zzf000(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.skyblockcatia.json:EntityPlayerSPMixin failed injection check, (0/1) succeeded. Using refmap mixins.skyblockcatia.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[SkyBlockcatia-1.8.9-1.0.14.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
	... 14 more
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Runtime.exit(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.System.exit(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:02:39] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[17:02:39] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[17:02:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[17:02:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[17:02:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[17:02:39] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main"

**Comment by SteveKunG** [comment]
Mod list?

**Comment by fmpreferences** [comment]
After some testing, the issue seems to be this with this mod, which has not been updated since 2019:
https://www.curseforge.com/minecraft/mc-mods/better-sprinting
however, here is a full list of my mods in case it turns out to have other conflicts:
Autotip 3.0
Better Sprinting 2.3.0
Danker's Skyblock Mod 1.8.4
ItemPhysic Lite 1.3
Patcher 1.4.1
Perspective Mod 1.0
OptiFine L6-pre1
SBCustomMobTex 1.4
Scrollable Tooltips 1.3
SkyblockAddons 1.6.0-beta.6
SyblockCatia 1.0.14
Waila 1.6.0-B3
