### ISSUE TITLE
game crush

### ISSUE THREAD

**Issue by tianawa** [SteveKunG/SkyBlockcatia#86]
i got a game crush
WARNING: coremods are present:
  FMLLoadingPlugin (Skytils-0.1.2-pre10.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  HCTweaker (HUDCaching-1.8-REL-for-MC1.8.9.jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.8.9-1.5.5.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 21-6-9 ??7:06
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/layers/LayerCustomHead
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:28)
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:18)
	at net.minecraft.client.renderer.entity.RenderSkeleton.<init>(SourceFile:15)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:163)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.layers.LayerCustomHead
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirect$renderEnchantedSkull$zgb000(Lnet/minecraft/client/renderer/tileentity/TileEntitySkullRenderer;FFFLnet/minecraft/util/EnumFacing;FILcom/mojang/authlib/GameProfile;ILnet/minecraft/entity/EntityLivingBase;FFFFFFF)V in mixins.skyblockcatia.json:renderer.entity.layers.LayerCustomHeadMixin failed injection check, (0/1) succeeded. Using refmap mixins.skyblockcatia.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:938)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:322)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:280)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:28)
	at net.minecraft.client.renderer.entity.RenderBiped.<init>(SourceFile:18)
	at net.minecraft.client.renderer.entity.RenderSkeleton.<init>(SourceFile:15)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:163)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	ct.js modules: [Module{name=AntiDoubleDeath,folder=.\config\ChatTriggers\modules\AntiDoubleDeath,metadata=ModuleMetadata(name=AntiDoubleDeath, version=1.2.0, entry=main.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Dolphin0xyz, description=This module prevents you getting wiped from the double death glitch by closing your client when you die, (with the vanilla death screen, you don't actually die on hypixel normally). Run /antidoubledeath to toggle the module, defaut is on. It only works if the server ip includes "hypixel"., requires=[SettingsManager, FileUtilities], helpMessage=&eRun &6/antidoubledeath &e for the settings., ignored=null, isRequired=false)}, Module{name=CustomTabCompletions,folder=.\config\ChatTriggers\modules\CustomTabCompletions,metadata=ModuleMetadata(name=CustomTabCompletions, version=1.0.2, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=SirHyperNova, description=A module that allows you to add a custom tab completion function to commands., requires=null, helpMessage=null, ignored=null, isRequired=true)}, Module{name=DeepProxy,folder=.\config\ChatTriggers\modules\DeepProxy,metadata=ModuleMetadata(name=DeepProxy, version=2.0.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Ecolsson, description=null, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonMilestones,folder=.\config\ChatTriggers\modules\DungeonMilestones,metadata=ModuleMetadata(name=Dungeon Milestone Tracker, version=1.0.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Track Milestone, requires=[PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=DungeonUtilities,folder=.\config\ChatTriggers\modules\DungeonUtilities,metadata=ModuleMetadata(name=DungeonUtilities, version=0.9.9, entry=loader.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=DwarvenUtilities,folder=.\config\ChatTriggers\modules\DwarvenUtilities,metadata=ModuleMetadata(name=DwarvenUtilities, version=1.0.4, entry=loader.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=&aUse &6/mines &ato open settings.

&7Support server: &bhttps://discord.gg/knjSZSC
, requires=[SettingsManager, PersistentData], helpMessage=null, ignored=null, isRequired=false)}, Module{name=Easy,folder=.\config\ChatTriggers\modules\Easy,metadata=ModuleMetadata(name=Easy, version=1.1.1, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Allows you to say EZ on Hypixel. Does not trigger on server commands., requires=[SettingsManager], helpMessage=null, ignored=null, isRequired=false)}, Module{name=FileUtilities,folder=.\config\ChatTriggers\modules\FileUtilities,metadata=ModuleMetadata(name=FileUtilities, version=2.5.0, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=Dolphin0xyz, description=Utilities for files, requires=null, helpMessage=null, ignored=null, isRequired=true)}, Module{name=FishingUtilities,folder=.\config\ChatTriggers\modules\FishingUtilities,metadata=ModuleMetadata(name=FishingUtilities, version=1.4.0, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=null, requires=[SettingsManager], helpMessage=null, ignored=null, isRequired=false)}, Module{name=PersistentData,folder=.\config\ChatTriggers\modules\PersistentData,metadata=ModuleMetadata(name=PersistentData, version=1.1.3, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Easily store data that persist between game and ct reloads, requires=[DeepProxy], helpMessage=null, ignored=null, isRequired=false)}, Module{name=PromiseV2,folder=.\config\ChatTriggers\modules\PromiseV2,metadata=ModuleMetadata(name=PromiseV2, version=1.0.4, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=McPqndq, description=Promise polyfill, requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=PuzzlerSolver,folder=.\config\ChatTriggers\modules\PuzzlerSolver,metadata=ModuleMetadata(name=PuzzlerSolver, version=null, entry=index.js, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Dwarven Mines puzzler solver for skyblock., requires=null, helpMessage=null, ignored=null, isRequired=false)}, Module{name=SettingsManager,folder=.\config\ChatTriggers\modules\SettingsManager,metadata=ModuleMetadata(name=SettingsManager, version=1.2.1, entry=null, asmEntry=null, asmExposedFunctions=null, tags=null, pictureLink=null, creator=null, description=Autogenerates a settings file and gui based on the object created and registers. Example usage can be found in UseExample.js, requires=null, helpMessage=null, ignored=null, isRequired=false)}]
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 451197720 bytes (430 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCH	apec{1.9.2} [Apec] (Apec-1.9.2.jar) 
	UCH	BazaarNotifier{1.4.0} [BazaarNotifier] (BazaarNotifier-1.4.0.jar) 
	UCH	cowlection{1.8.9-0.13.0} [Cowlection] (Cowlection-1.8.9-0.13.0.jar) 
	UCH	ct.js{1.3.0} [ChatTriggers] (ctjs-1.3.0-1.8.9.jar) 
	UCH	Danker's Skyblock Mod{1.8.6} [Danker's Skyblock Mod] (Danker's Skyblock Mod - 1.8.6.jar) 
	UCH	hudcaching{1.7-REL} [HUDCaching] (HUDCaching-1.8-REL-for-MC1.8.9.jar) 
	UCH	notenoughupdates{2.0.0-REL} [NotEnoughUpdates] (NotEnoughUpdates-2.0-PRE27.jar) 
	UCH	patcher{1.5.1} [Patcher] (Patcher-1.5.1 (1.8.9).jar) 
	UCH	text_overflow_scroll{1.3} [Scrollable Tooltips] (Scrollable Tooltips-1.3 (1.8.9).jar) 
	UCH	skyblockaddons{1.5.5} [SkyBlock Addons] (SkyblockAddons-1.8.9-1.5.5.jar) 
	UCH	skyblockcatia{1.1.2} [SkyBlockcatia] (SkyBlockcatia-1.8.9-1.1.2.jar) 
	UCH	skytils{0.1.2-pre10} [Skytils] (Skytils-0.1.2-pre10.jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (Skytils-0.1.2-pre10.jar)
  
FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
HCTweaker (HUDCaching-1.8-REL-for-MC1.8.9.jar)
  io.github.moulberry.hudcaching.asm.ClassTransformer
ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
CTJSLoadingPlugin (ctjs-1.3.0-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.8.9-1.5.5.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.48' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §r§lFurfSky §6§lReborn §8§lFL §8§l[§71.3§8§l] (2).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
 im using forge

**Comment by SteveKunG** [comment]
Fixed in 1.2.0.
